### ISSUE TITLE
ci/cd premerge logs associated with wrong commit hash

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAI#2833]
**Describe the bug**
to reproduce this issue:
- create a PR from a fork
- `/build` trigger the blossom-ci pipeline
- check the details of the pipeline
- the highlighted commit hash should correspond to the head of this fork's branch but it's currently not the case
![Screenshot 2021-08-24 at 17 13 14](https://user-images.githubusercontent.com/831580/130652431-d99cfd0d-369f-4c6c-960c-9bb3403bec9f.png)

**Comment by madil90** [comment]
This has been resolved. Please see the internal GitLab

**Comment by wyli** [comment]
> This has been resolved. Please see the internal GitLab

it seems it's not resolved, for example [this run](https://github.com/Project-MONAI/MONAI/actions/runs/1185359541) still has the dev's head as commit hash https://github.com/Project-MONAI/MONAI/commit/6dc9b3ec3ba3c41cd41bb5981abb6a7bb090745c, instead of the PR's head af02e97b54dfff34502912189acf0eda2e07a84f.

**Comment by wyli** [comment]
this is addressed when the workflow is triggered by the commenting
