### ISSUE TITLE
ITKReader doesn't return numpy array

### ISSUE THREAD

**Issue by Nic-Ma** [Project-MONAI/MONAI#2899]
**Describe the bug**
Currently, we use the `itk.array_view_from_image()` to get data array:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/image_reader.py#L316
But actually, it's not numpy array, so following logic which depends on numpy.ndarray type will fail.
```py
loader = LoadImage()
img, meta = loader(dicom_path)
print(type(img))
```
Get the output:
```
<class 'itk.itkPyBufferPython.NDArrayITKBase'>
```

**Comment by wyli** [comment]
NDArrayITKBase is a subclass of ndarray, shouldn't we enhance the relevant failing logic instead of converting them to ndarray, is this a duplicate ticket of #2885?

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Thanks for your suggestion, makes sense.
I updated the PR to update the relevant failing logic instead: https://github.com/Project-MONAI/MONAI/pull/2900.
Could you please help review it?

Thanks.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

After some testing, I feel it's better to also update ITK reader to use `np.asarray()`, because some operations of `NDArrayITKBase` is different from `ndarray`, very easy to cause unknown errors. For example:
```py
print(type(img))
ret = np.mean(img)
print(isinstance(ret, np.ndarray))
print(ret)

img1 = np.array([1, 2, 3])
print(type(img1))
ret1 = np.mean(img1)
print(isinstance(ret1, np.ndarray))
print(ret1)
```
The output is:
```
<class 'itk.itkPyBufferPython.NDArrayITKBase'>
True
-3.4086406e-07
<class 'numpy.ndarray'>
False
2.0
```
The check for `isinstance(mean, np.ndarray)` will fail here.

What do you think?

Thanks.

**Comment by wyli** [comment]
I think the problem is still that monai's current type conversion is not robust https://github.com/Project-MONAI/MONAI/blob/dev/monai/utils/type_conversion.py#L155, we should try to enhance it, instead of removing all the potential additional features brought by `NDArrayITKBase`.

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Not only the `type conversion`, the above `np.mean()` example comes from the `NormalizeIntensity` transform:
https://github.com/Project-MONAI/MONAI/blob/dev/monai/transforms/intensity/array.py#L593
It will cause error in the next line:
```py
if isinstance(_sub, (torch.Tensor, np.ndarray)):
    _sub, *_ = convert_to_dst_type(_sub, img)
    _sub = _sub[slices]
```

Thanks.

**Comment by wyli** [comment]
> After some testing, I feel it's better to also update ITK reader to use `np.asarray()`, because some operations of `NDArrayITKBase` is different from `ndarray`, very easy to cause unknown errors. For example:
> 
> ```python
> print(type(img))
> ret = np.mean(img)
> print(isinstance(ret, np.ndarray))
> print(ret)
> 
> img1 = np.array([1, 2, 3])
> print(type(img1))
> ret1 = np.mean(img1)
> print(isinstance(ret1, np.ndarray))
> print(ret1)
> ```
> 
> The output is:
> 
> ```
> <class 'itk.itkPyBufferPython.NDArrayITKBase'>
> True
> -3.4086406e-07
> <class 'numpy.ndarray'>
> False
> 2.0
> ```
> 
> The check for `isinstance(mean, np.ndarray)` will fail here.
> 
> What do you think?
> 
> Thanks.
@thewtex might be interested in this usability tests of `NDArrayITKBase `

**Comment by wyli** [comment]
Closing this via #2900 for now, please feel free to reopen and discuss further.
